const isDev = process.env.NEXT_PUBLIC_APPLICATION_ENV === 'development';

const DEV_ANNUAL_SUB_CODE = 'lXChK8Q7';
const PROD_ANNUAL_SUB_CODE = 'ujhcGPTs';

const DEV_MONTHLY_SUB_CODE = 'fUCkYhSw';
const PROD_MONTHLY_SUB_CODE = 'YUJDGtGo';

const DEV_SALE_30_PERCENT_OFF_CODE = 'g0LLdvco';
const PROD_SALE_30_PERCENT_OFF_CODE = 'OkLGNugW';

export const SUBSCRIPTION_CODES = {
  ANNUAL: isDev ? DEV_ANNUAL_SUB_CODE : PROD_ANNUAL_SUB_CODE,
  MONTHLY: isDev ? DEV_MONTHLY_SUB_CODE : PROD_MONTHLY_SUB_CODE,
  SALE_30_PERCENT_OFF: isDev ? DEV_SALE_30_PERCENT_OFF_CODE : PROD_SALE_30_PERCENT_OFF_CODE,
};
